.github/workflows/release.yml
.goreleaser.yaml

Adding more output to CI for troubleshooting

CI Verbose

---

.github/workflows/build.yml
Taskfile.yml
internal/control-api/client.go
internal/control-api/types.go
internal/models/cli.go
internal/node/config.go
internal/node/init.go
internal/node/running_vm.go
nex/node_linux_amd64.go
spec/monitor_test.go
spec/node_test.go
spec/spec_suite_test.go
test/run_test.go
test/stop_test.go
test/wasm_test.go

Setup spec/ and test/ directories, `task test` and `task clean` commands.
Add initial `nex node preflight` specs.

Setup spec/ and test/ directories and test task

---

.github/CODEOWNERS
agent/fc-image/rootfs.go

Updates permissions inside rootfs

Fix RootFS User Permissions

---

.github/workflows/build.yml
.github/workflows/release.yml
nex/nex.go

Closed #83 
TO use:
`logger.Log(ctx, LevelTrace, "Trace message")`

Add Trace Level to Logger

---

agent/fc-image/rootfs.go

Permissions Fix inside RootFS

---

agent/agent.go
agent/providers/api.go
agent/providers/lib/elf.go
agent/providers/lib/oci.go
agent/providers/lib/v8.go
agent/providers/lib/wasm.go
examples/echoservice/main.go
internal/node/machine_mgr.go

Addresses #91 
Currently having trouble both generating a root file system and getting this new agent to perform a handshake. My local setup is so messed up I can't rule out environmental issues.
Would love someone else to try out this PR and make sure that we can start and stop workloads still.

Give workloads a chance to gracefully shut down

---

.goreleaser.yaml

Adds rpm and deb to releases 

---

agent/fc-image/README.md

This makes it more clear on how to build the rootfs locally

RootFS Docs Update

---

internal/node/init.go
internal/node/machine_mgr.go
nex/node_linux_amd64.go
spec/node_test.go

This PR also includes some initial refactoring to make the `MachineManager` more... manageable.

Stop calling panic from node up and preflight

---

examples/echoservice/main.go

Adds better logging for echo server example

Better logging for echo example

---

internal/node/agentcomms.go
internal/node/config.go
internal/node/controlapi.go
internal/node/machine_mgr.go
internal/node/node.go
internal/node/nodeproxy.go
internal/node/payload_cache.go
internal/node/running_vm.go
spec/node_test.go
spec/spec_suite_test.go

This PR provides testing of the deployment of each of the workload types.
Some additional incremental refactoring can also be expected.
Closes https://github.com/synadia-io/nex/issues/40.

Additional testing and incremental refactor

---

agent/agent.go
internal/agent-api/types.go
internal/node/machine_mgr.go
internal/node/running_vm.go

This commit handles some small cleanup items to make things more consistent.

Set VM metadata outside of VM creation

---

internal/node/controlapi.go

Fix running workloads count display

---

internal/node/prereq.go
nex/node.go
nex/node_up_preflight.go

Updates build tags for full node capabilities in ARM binaries
closed #139

adds node up/preflight to arm binaries

---

internal/node/prereq.go

corrects where rootfs is downloading from

---

internal/node/services/lib/keyvalue.go

ngs needs this value set to create streams

---

go.mod
go.sum
internal/node/config.go
nex/nodes.go

Random name when not provided

---

nex/nex.go
nex/update.go

alerts on new nex version

---

internal/agent-api/types.go
internal/node/workload_mgr_events.go
spec/node_test.go

This PR adds initial specs for the v8 http host service.

Add v8 http host service specs

---

spec/node_test.go

update logger in tests

---

internal/node/node.go

I didn't recognize this when I first reviewed the PR, but we can publish heartbeats with one less goroutine.

Publish heartbeats on the main node goroutine

---

internal/node/workload_mgr.go

node info had wrong field for workload description

---

internal/models/cli.go
internal/node/init.go
nex/node_up_preflight.go

adds ability for preflight to create config

---

internal/models/cli.go
internal/nats-logger/nlogger.go
nex/nex.go

Multiple logger options

---

control-api/types.go
internal/node/controlapi.go

adds the node's target xkey to both ping responses

---

.goreleaser.yaml
internal/fc-image/rootfs.go
internal/models/cli.go
internal/node/init.go
internal/node/node.go
internal/node/prereq.go
nex/nex.go
nex/rootfs.go
nex/upgrade.go
spec/node_test.go

Fixes upgrading in place

---

internal/models/config.go
internal/node/workload_mgr.go

Makes agent handshake timeout configurable

---

.github/workflows/release.yml

Add CI trigger

---

go.mod
go.sum
internal/node/prereq.go

This reverts commit b6031e61e2274de14cb9aad6feb5a4b8dc765281.

Revert "Dependency Download Progress (#213)"

---

control-api/client.go
internal/models/cli.go
nex/nex.go
nex/nodes.go

Reason: helps identify nodes a little easier when starting workloads

Add detail to list node command

---

control-api/events.go
control-api/types.go
internal/models/cli.go
internal/node/controlapi.go
internal/node/node.go
nex/node.go
nex/nodes.go

Adds Nexus name to `node up`

---

go.mod
go.sum

Dependabot Findings

---

.goreleaser.yaml
agent/agent.go
agent/providers/api.go
agent/providers/lib/native.go
control-api/run.go
control-api/types.go
internal/agent-api/types.go
internal/models/cli.go
internal/models/config.go
internal/models/node_capabilities.go
internal/models/node_darwin.go
internal/models/node_linux_amd64.go
internal/models/node_linux_arm64.go
internal/models/node_windows.go
internal/models/utils.go
internal/node/config.go
internal/node/controlapi.go
internal/node/node.go
internal/node/processmanager/firecracker_procman.go
internal/node/workload_mgr.go
internal/node/workload_mgr_events.go
nex/devrunner.go
nex/nex.go
nex/tui/home/data.go
spec/node_linux_test.go
spec/node_windows_test.go
test/wasm_test.go

Reconfigure Default Workload Types

---

.github/workflows/ltb.yml
control-api/client.go
control-api/types.go
internal/node/controlapi.go
nex/devrunner.go
nex/nex.go
nex/nodes.go
nex/tui/home/model.go
spec/node_linux_test.go
spec/node_windows_test.go

Closes https://github.com/synadia-io/nex/issues/239

Support optional ping request for filtering nodes

---

nex/nodes.go

Lameduck Indicator 

---

internal/models/cli.go
internal/node/workload_mgr.go
nex/nex.go
nex/runner.go

Fix Jetstream Setting

---

.github/workflows/issue_create.yml

automates adding issues to project

---

nex/pprof.go

adds pprof server behind debug tag

---

.goreleaser.yaml

stops automarking release latest

---

internal/node/node.go
internal/node/workload_mgr.go

honor autostart jsdomain setting

---

nex/nex.go
nex/nodes.go

adds short form table to info output

---

internal/node/node.go

adds debug output for connection state changes

---

agent/agent.go

attempts host handshake 3 times now before giving up

---

internal/models/cli.go
internal/models/config.go
internal/node/init.go
internal/node/preflight/preflight.go
nex/node.go

install missing deps without prompt

---

Dockerfile
README.md

This will only work in no-sandbox mode

Adds Dockerfile 

---

examples/native_hostservice/main.go
examples/native_hostservice/nex.config.json
internal/node/workload_mgr.go

Native Workload + Host Services Example

---

README.md

Updates some init steps

---

control-api/client.go

Addresses #340 
Now uses defer to attempt to clean up the subscription used for ping and gather operations.

clean up subscriptions from gather operations

---

control-api/run.go
examples/native_hostservice/nex.config.json
examples/nodeconfigs/hostservices_config.json
internal/models/config.go
internal/node/workload_mgr.go
nex/devrunner.go
nex/nex.go
nex/runner.go
test/run_test.go

HS Config Env

---

internal/models/cli.go
internal/node/node.go
nex/node.go

Add node tags via CLI

---

internal/models/cli.go
internal/node/node.go
nex/node.go

Adds nosandbox flag to CLI

---

internal/models/cli.go
nex/nex.go
nex/nodes.go

The diff here is annoying, but none of the table code changed...just wrapped in a JSON bool

adds ability to output in json for some CLI commands

---

.github/workflows/release_candidate.yml

GHA for Release Candidates

---

.github/workflows/docker.yml
.github/workflows/release_candidate.yml
Dockerfile

Add GHA for Docker

---

.goreleaser.yaml

goreleaser fix  nex only in linux packages

---

internal/node/workload_mgr.go

trigger subjects are now queue subscriptions

---

.github/workflows/smoke.yml

adding smoke test

---

README.md
_scripts/otel/grafana/provisioning/dashboards/nex.json
agent/README.md
control-api/README.md
control-api/client.go
docs/getting_started.md
internal/fc-image/README.md
nex/README.md
nex/devrunner.go
nex/nex.go
nex/nodes.go
nex/tui/home/model.go
nex/tui/init.go
nex/upgrade.go
spec/node_linux_test.go
spec/node_nosandbox_test.go

The other edits are due to my editor's auto-formatting on save, so those should be harmless.

Rename remaining NEX -> Nex instances

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/defect.yml
.github/ISSUE_TEMPLATE/proposal.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ltb.yml
.gitignore
.goreleaser.yaml
cmd/nex/node.go
node/actors/agent_manager.go
node/actors/internal_nats_server.go
node/node.go

Moving CI to vnext

---

node/actors/logger.go
node/node.go

Supervisor Tree Logger

---

README.md

Move over start of README

---

cmd/nex/node.go
node/actors/agent_manager.go
node/actors/app.go
node/actors/control_api.go
node/actors/events.go
node/actors/host_services.go
node/actors/internal_nats_server.go
node/actors/supervisor.go
node/node.go
node/node_test.go

Remaining work pulled over from vnext

General Code Cleanup 

---

cmd/nex/go.sum
cmd/nex/main.go
cmd/nex/node.go
models/node_options.go
node/node.go

removes final references to ergo

---

cmd/nex/node.go
node/actors/internal_nats_server.go
node/actors/signal_reset_unix.go
node/actors/signal_reset_windows.go
node/node.go

Signal Capture Reset

---

api/nodecontrol/client.go
api/nodecontrol/gen/start_workload_request.go
api/nodecontrol/start-workload-request.json
cmd/nex/cli_unix.go
cmd/nex/cli_windows.go
cmd/nex/table.go
cmd/nex/workload.go
node/actors/control_api_conversions.go

WIP: depends on #413...just look at latest commit for now

Start/Stop Workloads CLI Command

---

api/nodecontrol/client.go
cmd/nex/go.mod
cmd/nex/go.sum
cmd/nex/helpers.go
cmd/nex/node.go
cmd/nex/workload.go
go.mod
go.sum
models/envelope.go
models/node_options.go
node/actors/control_api.go
node/node.go

Depends on #416
```
└─❯ go run . node ls
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                NATS Execution Nodes                                                               │
├───────┬──────────────────────────────────────────────────────────┬──────┬─────────┬────────┬───────────┬──────────────────────────┬───────┬───────┤
│ Nexus │ ID (* = Lameduck Mode)                                   │ Name │ Version │ Agents │ Workloads │ Uptime                   │ OS    │ Arch  │
├───────┼──────────────────────────────────────────────────────────┼──────┼─────────┼────────┼───────────┼──────────────────────────┼───────┼───────┤
│ nexus …
```

CLI Node List Command

---

node/internal/actors/os_procs.go
node/internal/actors/stop_process.go
node/internal/actors/stop_process_windows.go

Windows Graceful Stop 

---

cmd/nex/logger.go
cmd/nex/node.go
node/internal/actors/direct_start_agent.go

Adds the ability to hide workload logs

Workload Log Filter

---

node/node.go

Was setting start time too late

Fixes Uptime Bug

---

.github/workflows/ltb.yml
go.mod
go.sum
node/internal/actors/artifacts_test.go

Revert OCI Test

---

api/nodecontrol/client.go
cmd/nex/go.mod
cmd/nex/go.sum
cmd/nex/node.go
node/internal/actors/control_api_conversions.go
node/node.go

```
└─❯ go run . node info NAU55EVRD3Y3ACS5PUQWJEJFAWREEZPADZEFVYQGIBR7IT3I5QJFYSIE
Information about Node NAU55EVRD3Y3ACS5PUQWJEJFAWREEZPADZEFVYQGIBR7IT3I5QJFYSIE
Nexus: nexus
Node Name: noble-headquarters
Tags: nex.arch=amd64, nex.cpucount=20, nex.lameduck=false, nex.nexus=nexus, nex.node=noble-headquarters, nex.os=linux
Uptime: 11.399061301s
Version: 0.0.0
╭───────────────────────────────────────────────────────────────────────╮
│                           Running Workloads                           │
├────────────────────────┬─────────┬─────────────────────┬──────────────┤
│ Id                     │ Name    │ Start Time          │ Type         │
├────────────────────────┼─────────┼─────────────────────┼──────────────┤
│ 4EZnJEdiMs2UnEd5k28Z49 │ counter │ 2024-11-15 00:57:52 │ …
```

Adds Node Info Command 

---

cmd/nex/workload.go

Fixes OCI Auth 

---

.github/workflows/ltb.yml
.github/workflows/schema_generation.yml

Fix CI for merge

---

.gitignore
README.md
Taskfile.yaml

Added a readme to get started and modified the taskfile to build the nex binary into a target folder so it won't dirty the cmd/nex dir.

added a readme and building binary in target

---

.github/workflows/schema_generation.yml
cmd/nex/debug.go
cmd/nex/debug_noop.go
cmd/nex/node.go

Debug Build Tag

---

cmd/nex/cli_unix.go
cmd/nex/cli_windows.go
cmd/nex/logger.go
cmd/nex/main.go
cmd/nex/main_test.go
cmd/nex/monitor_test.go
cmd/nex/upgrade_test.go
models/node.go
models/subjects.go
node/internal/actors/control_api.go
node/internal/actors/direct_start_agent.go
node/internal/actors/direct_start_agent_test.go
node/node.go

Make `system` namespace a const

---

.github/workflows/codecoverage.yml

Remove custom filename from CI

---

.github/workflows/ltb.yml
node/internal/actors/internal_nats_server.go

Moves internal nats state to resource dir

---

cmd/nex/logger.go

Fixes subject for NATS logger
