synadia-io/nex

.goreleaser.yaml
Goreleaser needs sudo so that it can mount
=> add sudo to goreleaser

.goreleaser.yaml
because agent only in linux/x86 archive
=> goreleaser binary count setting

internal/node/prereq.go
Uses `MkdirAll` to precreate missing dependency directories.
=> Fixes #85 - precreates all pre-requisite directories if they're not there

.github/workflows/build.yml, Taskfile.yml, go.sum, internal/node/agentcomms.go, internal/node/controlapi.go, internal/node/events.go, internal/node/machine_mgr.go, internal/node/node.go, internal/node/telemetry.go, spec/node_test.go
This PR fixes the following issues:
- Publish `node_stopped` message prior to draining NATS connection
- Use noop meter provider when otel metrics are disabled -- this fixes a panic
The spec suite is now being called with `go run github.com/onsi/ginkgo/v2/ginkgo` when running locally (`task test`) as well as in GitHub actions.
=> Fixes related to `node_stopped` msg publish and otel panic

spec/spec_suite_test.go
The intent of this is to allow github actions runners to win the race to gracefully shutdown running node instances prior to the ginkgo suite exiting.
=> Add cooldown to spec suite cleanup

.gitignore, Taskfile.yml, internal/node/config.go, internal/node/prereq.go, internal/node/running_vm.go, spec/node_test.go
- adds `BinPath` to CNI node config and passes this through to CNI.
- defaults CNI bin path to match the process `PATH`, pre-pending `/opt/cni/bin` first.
- adds preflight support to check multiple directories instead of just one.
- defaults the user binaries directory list to match the process `PATH`, pre-pending `/usr/local/bin` first.
- if installation of missing dependencies is desired, they are installed in the first entry in the directory lists e.g. `/opt/cni/bin`, `/usr/local/bin` which preserves the current behaviour.
This change is designed to make it easier to integrate with Nix, where binaries are not installed in the usual places. More generally I think it provides better ergonomics to check in the `PATH`.
=> feat: search PATH for CNI plugins and required binaries

agent/fc-image/rootfs.go
This PR increases the default size of the agent rootfs image to 150 MiB.
=> Increase rootfs size

nex/devrunner.go
In many situations, including NGS/Synadia Cloud, you can't create object store buckets without specifying a maximum number of bytes. To keep the `devrun` option the easiest way to get started, this adds a max bytes of **100MB** to the configuration.
The worst case scenario is eventually the developer has a workload that's > 100MB, and they have to update the bucket configuration.
=> Adds max bytes setting to ad hoc storage for devrun

nex/nex.go
The `--loglevel` option was no longer being applied.
=> Fix default slog initialization

nex/nodes.go
Adds configurable friendly name to `node ls` output
```
╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                        NATS Execution Nodes                                        │
├──────────────────────────────────────────────────────────┬──────────┬─────────┬────────┬───────────┤
│ ID                                                       │ Hostname │ Version │ Uptime │ Workloads │
├──────────────────────────────────────────────────────────┼──────────┼─────────┼────────┼───────────┤
│ NCNEPHS6GWK33USX4NUTHQKFEW6NYVMHQD7R2MUOKX6NGZBOI4T2AJAP │ my-nex   │ 0.1.5   │ 30m17s │         0 │
╰──────────────────────────────────────────────────────────┴──────────┴─────────┴────────┴───────────╯
```
via 
```
{ …
```
=> Adds a friendly hostname tag to node ls output

agent/agent.go, agent/metadata.go
In order to eventually support the no-sandbox mode, agents will need a way to get the NATS internal IP and port and the workloadId that it's been assigned from the node.
This PR makes it so that if the `NEX_SANDBOX` environment variable both exists and contains the value "false", then the agent will skip the MMDS query. When the agent is running in a sandbox (firecracker + rootfs), the agent is running as an openrc service and so won't have that env var.
=> allow agent to pull its metadata from environment

agent/agent.go, internal/node/node.go, internal/node/processmanager/firecracker_procman.go, spec/node_test.go
The node spec suite now tests the node in sandbox and non-sandbox mode.
All node specs defined within `Describe("up")` are exercised within both sandbox and no-sandbox contexts.
=> Expand node test coverage for non-sandbox mode

control-api/events.go, internal/node/node.go
Every 30s the nodes now publish a heartbeat on the system namespace (the same as node_started and node_stopped)
`[#2] Received on "$NEX.events.system.heartbeat"`
```json
{
"data": {
"version": "development",
"node_id": "NDWH3KOZ4OOYD2EMSKMCZFYV7GIXRCQ77WTFLVMLYAQBNGNQXOWIFQNG",
"uptime": "30s",
"tags": {
"nex.arch": "amd64",
"nex.cpucount": "8",
"nex.os": "linux",
"nex.unsafe": "true",
"node_name": "euphoric-penny",
"simple": "yep"
},
"running_machines": 0
},
"datacontenttype": "application/json",
"id": "e851b5e2-07a6-449c-bc02-62ebf6f349ed",
"source": "NDWH3KOZ4OOYD2EMSKMCZFYV7GIXRCQ77WTFLVMLYAQBNGNQXOWIFQNG",
"specversion": "1.0",
"time": "2024-04-17T12:16:02.413190253Z",
"type": "heartbeat"
}
```
=> nodes now publish heartbeats

control-api/client.go, internal/node/controlapi.go, internal/node/workload_mgr.go, nex/nex.go, nex/nodes.go
You can now use a different `WPING` endpoint to have nodes _only_ reply to a ping if they're currently running the indicated workload, which can be the workload ID or the workload name.
So if you specify a workload ID, you should expect 0 or 1 nodes.
If you specify a workload name, you might get multiple nodes if that workload is scaled out.
Added the `--workload` option to the `node ls` command, so the end user doesn't need to know that this is a different ping subject under the hood.
=> Ping can now optionally filter by workload ID or name

_scripts/otel/otel-collector.yaml
Not needed for dev OTel and opens an unneeded port
=> Remove OtelCol healthcheck

agent/providers/lib/v8.go, examples/v8/echofunction/src/echofunction.js, examples/v8/echofunction/src/kv.js, examples/v8/echofunction/src/messaging.js, examples/v8/echofunction/src/objectstore.js, internal/agent-api/client.go, internal/agent-api/types.go, internal/node/services/lib/http.go, internal/node/services/lib/keyvalue.go, internal/node/services/lib/messaging.go, internal/node/services/lib/objectstore.go, internal/node/workload_mgr.go, spec/node_test.go
This PR cleans up the v8 host services provider implementation.
The agent v8 provider now exclusively requires and uses `Uint8Array` when:
- marshaling parameters included in functions called from javascript (`v8.Value` -> `[]byte`)
- unmarshaling raw bytes returned to functions called from javascript (`[]byte` -> `v8.Value`)
Additionally, the host services API has been cleaned up in preparation for formalizing an SDK (#170). Namely, the use of message headers and non-enveloped payloads have been made consistent across host services.
=> Cleanup host services

examples/nodeconfigs/public_nats_server.json, internal/models/config.go, internal/node/node.go
This PR allows users to configure and start a "userland" NATS server when starting a node.
Error handling inside of `node.init()` was not failing fast, resulting in discarded errors. This PR includes a fix to use `errors.Join` which allows the node to gracefully abort initialization using `shutdown()` instead of panicking.
Closes #168.
=> Add support for starting a userland NATS server

internal/node/workload_mgr.go
This PR fixes a regression caused by not calling `StopWorkload()` for each associated agent client in the workload manager.
If the workload manager has stopped a workload, attempts to stop the same workload as a side effect of handling a `workload_stopped` cloud event from the agent will fail, since that workload will no longer be resolved.
=> Fix regression causing workload-associated resources to leak

.github/workflows/ltb.yml, go.mod, go.sum, internal/node/prereq.go
* Uses `bubbletea` to add progress bar to `nex node prefilght`.
* Based largely on examples in the `bubbletea` repo.
* Attempts to be as minimal as possible, but `bubbletea` is geared towards full scale `tuis` so  there seemed to be quite a few hoops to hop through. 
~* Updates the `gha` to use `script` when running tests on `ubuntu` - this wraps the shell and mimics tty behavior since `gha` doesn't provide. See https://github.com/actions/runner/issues/241~
=> Dependency Download Progress

agent/agent.go, agent/providers/api.go, agent/providers/lib/elf.go, agent/providers/lib/oci.go, agent/providers/lib/v8.go, agent/providers/lib/v8_nop.go, agent/providers/lib/wasm.go, host-services/builtins/builtins_client.go, host-services/builtins/builtins_test.go, host-services/builtins/http.go, host-services/client.go, host-services/server.go, host-services/service_test.go, internal/agent-api/client.go, internal/node/services.go, internal/node/workload_mgr.go, test/wasm_test.go
This PR adds otel child span support for tracing host services execution.
Closes #132.
=> Add tracing to host services

.gitignore, agent/agent.go, internal/agent-api/client.go, internal/node/workload_mgr.go, test/panicker/main.go
The node will now ping all agent processes (pending or deployed/active). If the agent fails to respond, the node will remove that agent from its known agents pool and ask the procman to try and shut it down (which should be idempotent and safe).
The agent dying looks something like this:
```
cp3kus752omnmk6of1hg | [INFO] 2024-05-17 08:38:47 - Received signal: terminated workload_id=cp3kus752omnmk6of1hg from_agent=true
[INFO] 2024-05-17 08:38:47 - Agent command exited cleanly pid=227201
[WARN] 2024-05-17 08:38:49 - Agent failed to respond to ping error=nats: timeout
[WARN] 2024-05-17 08:38:49 - Lost contact with agent workload_id=cp3kus752omnmk6of1hg
[ERROR] 2024-05-17 08:38:49 - Failed to interrupt agent process agent_id=cp3kus752omnmk6of1hg pid=227201 err=os: process already finished
``` …
=> adds ping to agent process for client monitoring

nex/bin_validator.go, nex/devrunner.go, nex/nex.go
=> adding validation around binary types

.github/workflows/ltb.yml
This PR will allow for up to 3 attempts when running Windows specs in CI.
=> Retry failed windows specs up to 3 times in CI

.gitignore, control-api/run.go, examples/nodeconfigs/autostart_config.json, internal/models/config.go, internal/node/node.go
See the sample config in `nodeconfigs` for how this is set up. It's basically the key parameters from a run request, just applied automatically at startup.
Note that because of the anti-tamper protection, only a nex client using the same seeds from the node config will be able to terminate that workload (this is a good thing :tm: )
=> adds the ability to bootstrap workloads at node start

agent/agent.go, agent/logger.go, control-api/events.go, internal/agent-api/client.go, internal/agent-api/events.go, internal/node/events.go, internal/node/workload_mgr_events.go, nex/watch.go, spec/monitor_test.go
Also changes the source of an agent-originated cloud event to be prefixed by the carrying node, e.g. previous source was raw agent ID, new source is `Nxxxx-{agentId}`.
=> renames workload start/stop to deploy/undeploy

.gitignore, Taskfile.yml, agent/agent.go, agent/metadata.go, agent/providers/lib/v8.go, go.mod, host-services/builtins/keyvalue.go, host-services/client.go, host-services/server.go, host-services/service.go, internal/agent-api/client.go, internal/agent-api/types.go, internal/models/config.go, internal/node/controlapi.go, internal/node/internal-nats/config_template.go, internal/node/internal-nats/config_template_test.go, internal/node/internal-nats/internal_nats_server.go, internal/node/internal-nats/internal_nats_server_test.go, internal/node/node.go, internal/node/nodeproxy.go, internal/node/processmanager/firecracker_procman.go, internal/node/processmanager/process_mgr_linux.go, internal/node/processmanager/process_mgr_windows.go, internal/node/processmanager/spawn_procman.go, internal/node/services.go, internal/node/workload_mgr.go, internal/node/workload_mgr_events.go, spec/node_linux_test.go, spec/node_windows_test.go
This set of changes will make the internal NATS server multi-tenant safe by provisioning a user/account for each workload, and keeping the workload binary cache in a separate object store (one in each user account).
=> Preliminary support for account security in nats internal server

agent/agent.go, agent/providers/api.go, control-api/run.go, control-api/types.go, internal/agent-api/types.go, internal/models/cli.go, internal/models/config.go, internal/models/node_capabilities.go, internal/models/node_darwin.go, internal/models/node_linux_amd64.go, internal/models/node_linux_arm64.go, internal/models/node_windows.go, internal/node/config.go, internal/node/controlapi.go, internal/node/node.go, internal/node/workload_mgr.go, nex/devrunner.go, nex/nex.go, spec/node_linux_test.go, spec/node_windows_test.go, test/wasm_test.go
I know that newtypes are all the rage in other languages (esp. Haskell), but this is one time where it hurt us, because we had a newtype that was internal and required by external consumers.
=> moves nexworkload string newtype to controlapi

control-api/run.go, host-services/builtins/builtins_test.go, host-services/builtins/http.go, host-services/builtins/keyvalue.go, host-services/builtins/messaging.go, host-services/builtins/objectstore.go, host-services/client.go, host-services/server.go, host-services/service.go, host-services/service_test.go, internal/agent-api/types.go, internal/models/cli.go, internal/models/config.go, internal/node/controlapi.go, internal/node/node.go, internal/node/services.go, internal/node/workload_mgr.go, nex/nex.go
Each workload is now given its own unique/private host services connection. These connections are created using the following order of configuration (1 being the highest priority)
1. host services configuration on the deployment request
2. host services configuration supplied for the entire node
3. configuration copied from the node's control connection
=> Per-workload host services connections

go.mod, go.sum, internal/node/dns.go, internal/node/node.go, spec/spec_suite_test.go
This PR prevents a nex host running the embedded DNS resolver from being used by other devices on the same network.
This implements some trickery to bind the UDP listener for DNS to the configured CNI gateway without regard to the presence of required network interfaces. Once the interface has been created, the UDP listener is rebound on the same ephemeral port and the listener originally created on 0.0.0.0 is closed.
=> Use configured CNI subnet to lockdown DNS

control-api/run.go
Allows capital letters and underscores now as well as the original letters and numbers.
=> relax restrictions on workload name

control-api/client.go
This bug didn't show up when using the `nex` CLI directly because the CLI creates an empty/discard logger. When using the library with a logger, we'd constantly see:
```
[ERROR] 08:49:00 - failed to extract envelope err=no data for envelope nats_msg.Data=[]
```
This is because all of the code in the nexus client responsible for gathering multiple responses didn't account for getting a response with no data (this happens when there's "no responders", etc)
The new code will skip all processing if there's no data to process.
=> fixes bug in gather processing

internal/models/config.go, internal/node/config.go, internal/node/controlapi.go, internal/node/controlapi_test.go, internal/node/node.go
1. Always rejects a certain set of subject spaces for functions: `$SYS.>`, `$JS.>`, and `$NEX.>`. 
2. You can add more trigger subject restrictions in the node config using the `deny_trigger_subjects` field
This is what it looks like to try and devrun a function with a denied trigger subject:
```
❯ ./nex devrun ../examples/v8/echofunction/src/echofunction.js --trigger_subject='$NEX.events.>' --type=v8
Reusing existing issuer account key: /home/kevin/.nex/issuer.nk
Reusing existing publisher xkey: /home/kevin/.nex/publisher.xk
[ERR] 2024-06-18 14:21:56 - failed to devrun workload err=The trigger subject $NEX.events.> overlaps with subject(s) in this node's deny list
```
=> Adds the ability to deny certain trigger subjects for functions

nex/nex.go
for consistency so that a subscription to `$NEX.logs.{namespace}.>` will always end in a namespace, this adds the `system` token to the node-scoped logs that are emitted via the `stdout` and `stderr` tokens
=> puts node-wide logs in the system namespace

internal/models/config.go, internal/node/node.go
This will close #292 : 
1. Cause a node shutdown if any error occurs while trying to start an autostart workload
2. Can now indicate whether an autostart workload should be `essential` in the autostart portion of the node config.
=> fail fast autostarts

internal/agent-api/client.go, internal/models/config.go, internal/node/controlapi.go, internal/node/workload_mgr.go
If a `node_limits` section is specified in the node configuration, then we can now specify the following limits:
* max bytes for an individual workload (disk size, not ram)
* max bytes total for the entire node
* max number of running workloads for the node, regardless of size
=> adds optional node limits

internal/node/workload_mgr.go
I genuinely don't know if this makes things better, worse, or has no effect. It's had no effect on the spec tests.
For consistency sake, the `SelectRandomAgent` was the only method that didn't honor the pool mutex, so I'm adding that in.
=> uses pool mutex to select random agent

internal/node/node.go
Prevents the panic as described in #277
=> prevents a panic during shutdown when there's no NATS connection

agent/agent.go, internal/node/processmanager/firecracker_procman.go, internal/node/processmanager/running_vm.go
In the current implementation, we start a firecracker VM _before_ we allocate the credentials that agent is going to need to connect. To avoid the situation where the agent starts before its credentials have been added to the internal NATS server, this PR makes sure the credentials are allocated first.
Credentials are already allocated first for the no-sandbox mode.
=> allocate credentials before starting firecracker VM

.github/workflows/ltb.yml, Taskfile.yml, agent/agent.go, agent/providers/lib/v8.go, agent/providers/lib/wasm.go, control-api/client.go, control-api/types.go, internal/agent-api/client.go, internal/models/cli.go, internal/models/config.go, internal/node/controlapi.go, internal/node/init.go, internal/node/internal-nats/config_template.go, internal/node/internal-nats/config_template_test.go, internal/node/internal-nats/internal_nats_server.go, internal/node/internal-nats/internal_nats_server_test.go, internal/node/node.go, internal/node/preflight/init.go, internal/node/preflight/preflight.go, internal/node/processmanager/firecracker_procman.go, internal/node/processmanager/process_mgr.go, internal/node/processmanager/running_vm.go, internal/node/processmanager/spawn_procman.go, internal/node/workload_mgr.go, internal/node/workload_mgr_events.go, nex/nodes.go, spec/node_linux_test.go, spec/node_nofc_test.go, spec/spec_suite_test.go
This PR addresses the following instability issues:
- the internal NATS server had no mutex around the modification of the map that stores creds; in addition, we are now caching the first NATS connection created for the node to communicate with running agents
- MachineManager and ProcessManager implementations were not synchronized; MachineManager now returns data about agents and does not lookup agents/workloads using the ProcessManager interface
- deploying workloads using the controlapi package now implements logic to retry in the event no agent is available
- the spec harness was ill-equipped to handle testing multiple machines in the pool
- nex node info output has been updated to include more data
=> Fix stability of workload deployment and process accounting

agent/providers/lib/native.go, agent/providers/lib/v8.go, examples/nodeconfigs/hostservices_config.json, examples/v8/echofunction/src/http.js, examples/v8/echofunction/src/kv.js, examples/v8/echofunction/src/messaging.js, examples/v8/echofunction/src/objectstore.js, host-services/builtins/builtins_client.go, host-services/builtins/builtins_test.go, host-services/builtins/keyvalue.go, host-services/builtins/objectstore.go, host-services/server.go, host-services/service_test.go, internal/agent-api/client.go, spec/spec_suite_test.go
This PR does a few main things:
* changes behavior so that host services resources (currently kv, objectStore) are _never_ automatically provisioned
* JS API for host services has been changed as per #332 
* Fixed a bug in host services calls that didn't return an error propagated from the service itself
=> remove auto provision, simplify js hs api

control-api/run.go, control-api/utils.go, internal/agent-api/client.go, internal/agent-api/types.go, internal/node/controlapi.go, internal/node/node.go, internal/node/workload_mgr_events.go
#337 removed properties from the agent's version of the `DeployRequest` struct (now called `AgentWorkloadInfo` as a result of #337). This prevented essential workloads from being restarted due to missing the encrypted environment and sender public key.
=> Fix regression related to AgentWorkloadInfo refactor

internal/node/node.go, internal/node/workload_mgr_events.go
Fix a bug introduced by looking up the object hash for autostart workload artifacts via jetstream without consideration of a configured jetstream domain.
=> Ensure jetstream domain is configured for object digest lookup

internal/models/cli.go, internal/node/node.go, nex/node.go
Unfortunately, the default on the --no-sandbox flag was overriding the config everytime....this checks before it overrides
=> Sandbox Default

host-services/builtins/objectstore.go, host-services/inmem/keyvalue.go, host-services/inmem/objectstore.go, test/inmem_hostservices/main.go
For nex developers who are looking to test various components in isolation, this gives us in-memory versions of the kv and object store (the http and messaging ones already work in isolation). Just use the new binary in the `test/inmem_hostservices` folder
=> add in-memory host services for testing

agent/agent.go, internal/models/config.go, internal/node/controlapi.go, nex/runner.go
Make run requests behave "more synchronously" and increase default agent handshake timeout.
=> Make run requests more stable

node/actors/agent_supervisor.go, node/actors/control_api.go, node/actors/direct_start_agent.go, node/actors/external_agent.go
Note that there is some implementation stuff that hasn't happened yet because neither of the agent actors are currently  maintaining their workload list. Once they do that, we can fill in the "make this real" bits with the actual list of workloads.
=> adds a sample actor interaction for querying the list of running workloads from the info endpoint

agents/common/agent_client.go, node/internal/actors/external_agent.go, node/internal/actors/internal_nats_server.go, node/node.go
Creates an instance of the new `AgentClient` and renames some fields to make it more clear when the actor is managing creds for its own internal use versus passing them down into the agent binary. This should be the last of the "pre" PRs before I push up a PR with a functioning external agent.
=> fixes the connection and credentials

.github/workflows/codecoverage.yml, .github/workflows/ltb.yml, .github/workflows/schema_generation.yml
CI steps to visualize code coverage moving forward
=> code coverage ci

node/internal/actors/direct_start_agent.go, node/internal/actors/os_procs.go, node/internal/actors/process_actor.go
=> Process Actor Refactor

api/nodecontrol/client.go, api/nodecontrol/client_test.go, api/nodecontrol/gen/node_info_response.go, api/nodecontrol/gen/node_ping_response.go, api/nodecontrol/node-info-response.json, api/nodecontrol/node-ping-response.json, cmd/nex/node.go, go.mod, go.sum, models/node.go, models/node_options.go, node/internal/actors/control_api.go, node/internal/actors/control_api_conversions.go, node/node.go
=> Missing Control API Unit Tests

api/nodecontrol/client_test.go, cmd/nex/go.sum, test/auction_workload_start_test.go, test/copy_workload_test.go, test/helpers.go, test/lameduck_test.go, test/node_test.go, test/workload_test.go
This PR moves existing tests to use the assertion package.
Additionally, it moves a handful of test helper functions to the `test` package
=> Migrate to assertion package

api/nodecontrol/client.go, api/nodecontrol/gen/start_workload_response.go, api/nodecontrol/gen/stop_workload_response.go, api/nodecontrol/start-workload-response.json, api/nodecontrol/stop-workload-response.json, cmd/nex/node.go, cmd/nex/workload.go, models/node_options.go, node/internal/actors/control_api.go, node/node.go, test/copy_workload_test.go, test/helpers.go, test/workload_test.go
=> Optional Message to Start/Stop Workloads
